class Idsr(object):
    idsr_dict = {
        'reporting_date': '',
        'county_code': '',
        'facility_code': '',
        'case_id': '',
        'patient_record_id': '',
        'reporting_health_facility': '',
        'reporting_county': '',
        'reporting_district': '',
        'condition_of_alert': '',
        'patient_first_name':'',
        'patient_middle_name': '',
        'patient_last_name': '',
        'patient_gender': '',
        'age_of_patient': '',
        'patient_date_of_birth': '',
        'patient_age_years': '',
        'patient_age_months': '',
        'patient_age_days': '',
        'patient_county_of_residence': '',
        'patient_district_of_residence': '',
        'patient_community_of_residence': '',
        'head_of_household': '',
        'patient_parent_name': '',
        'patient_parent_phone_number': '',
        'patient_cross_border_in_last_month': '',
        'case_detected_at_community_level': '',
        'date_of_disease_onset': '',
        'date_patient_seen': '',
        'patient_type': '',
        'case_outcome': '',
        'case_classification':'',
        'reporting_person_first_name': '',
        'reporting_person_last_name': '',
        'phone_number_of_person_reporting': '',
        'name_of_person_collecting_specimen': '',
        'phone_number_of_person_collecting_specimen': '',
        'health_worker_comments': '',
        'vaccinated_for_disease': '',
        'num_of_vaccinations': '',
        'date_of_most_recent_vaccination': '',
        'date_of_specimen_collection': '',
        'date_specimen_sent_to_lab': '',
        'specimen_type': '',
        'lab_analysis_requested': '',
        'lab_specimen_id': '',
        'final_lab_result': '',
        'date_results_reported': '',
        'totally_filled': '',
        'bika_client_id': '',
        'bika_patient_id': '',
        'bika_ar_id': '',
        '_id':'',
        'patient_record_id_old':'',
        'creator':'',
        'creation_date':'',
        'lastmodification_date': '',
    }

    def __init__(self, id):
        self.id = id
